title: Default Page

columns:
  image:
    width: 1/2
    sections:
      image:
        type: fields
        fields:
          library:
            type: files
            template: image
            uploads: image
            layout: cards
            # multiple: false
            # min: 1
            # max: 1
            image:
              icon: true
              ratio: 4/3
              back: white
              cover: true
  copy:
    width: 1/2
    sections: 
      copy:
        type: fields
        fields:
          blocks:
            label: Testi
            type: blocks
            fieldsets:
              - maintext
              - title
              - accordion

