title: Default Page

columns:
  image:
    width: 1/2
    sections:
      image:
        type: fields
        fields:
          cover:
            label: Immagine
            type: files
            layout: cards
            size: huge
            query: site.images
            multiple: false
            uploads: false
            image:
              icon: true
              ratio: 1/1
              back: white
              cover: true
  copy:
    width: 1/2
    sections: 
      copy:
        type: fields
        fields:
          blocks:
            label: Testi
            type: blocks
            fieldsets:
              - maintext
              - title
              - accordion

