title: Site

tabs:
  home:
    label: WEBSITE
    icon: grid-full
    columns:
      homepage:
        width: 2/3
        sections:
          homepage:
            type: pages
            label: Homepage
            layout: list
            sortable: false
            template: 
              - home
            create: false
            num: 0
            image:
              icon: true
              ratio: 1/1
              back: white
              cover: true 
          pages:
            type: pages
            label: Pagine
            layout: list
            template: 
              - page
            image:
              icon: true
              ratio: 1/1
              back: white
              cover: true    
      sidebar:
        width: 1/3
        sections:
          global:
            type: fields
            fields:
              contact:
                label: Contatti
                type: email
  seo:
    label: SEO
    icon: circle
    columns:
      main:
        width: 2/3
        sections:
          seocontent:
            type: fields
            fields:
              description:
                label: Descrizione
                type: textarea
                buttons: false
              keywords:
                label: Keywords
                type: tags         
      image:
        width: 1/3
        sections:
          image:
            type: fields
            fields:
              ogimage:
                label: Immagine di copertina
                type: files
                template: image
                uploads: image
                layout: cards
                size: huge
                multiple: false
                image:
                  icon: true
                  ratio: 1/1
                  back: white
                  cover: true





