title: Site

tabs:
  home:
    label: WEBSITE
    icon: grid-full
    columns:
      main:
        width: 3/4
        sections:
          pages:
            type: pages
            template: 
              - page
              - home
            image:
              icon: true
              ratio: 1/1
              back: white
              cover: true
      sidebar:
        width: 1/4
        sections:
          global:
            type: fields
            fields:
              contact:
                label: Contatti
                type: email
  seo:
    label: SEO
    icon: circle
    columns:
      main:
        width: 1/2
        sections:
          seocontent:
            type: fields
            fields:
              description:
                label: Descrizione
                type: textarea
                buttons: false
              keywords:
                label: Keywords
                type: tags         
      image:
        width: 1/2
        sections:
          image:
            type: fields
            fields:
              ogimage:
                label: Immagine di copertina
                type: files
                template: image
                uploads: image
                layout: cards
                size: huge
                multiple: false
                image:
                  icon: true
                  ratio: 1/1
                  back: white
                  cover: true





